### ISSUE TITLE
Remove string literals from action creators/reducers

### ISSUE THREAD

**Issue by mikeyhogarth** [mikeyhogarth/cocktails#113]
Currently we have this kind of thing going on;

```
// actions
export function loadIngredients(payload) {
  return { type: "LOAD_INGREDIENTS", payload };
}

// reducers
      case "LOAD_INGREDIENTS":
```

Where the string `"LOAD_INGREDIENTS"` is declared twice (and in fact every time a reducer is run). Aside from being (albeit minimally) inefficient, it also adds an extra level of churn if you ever want to change them. There are a couple of ways we could do this;

1. Introduce an `actionTypes.js` file, put the constants in there, and reference them from `actions/index.js` and `reducers/index.js`.

2. Introduce a supporting library such as [Redux Actions](https://redux-actions.js.org/) to help us with this. 

I actually don't feel particularly strongly either way - (1) will be simpler and overall be less code in the bundle, but (2) will be neater and will result in less code for us to actually write and work with.

**Comment by zelol** [comment]
I can work on it. Is it okay if I take my time cause I'm a little newbie on the github game :)

**Comment by mikeyhogarth** [comment]
Sure - assign yourself the ticket though.

**Comment by mikeyhogarth** [comment]
No pressure on this, I just make these tickets when I think of them and put them up so I don't forget, and then I pick them up when I get a spare minute. 

Do you want me to leave this one for you to do then? (if you are particularly interested in doing it then be my guest but am more than happy to pick it up myself)

**Comment by zelol** [comment]
I'd like to do something about it :) I'll come back to you if I have any difficulties.
thank you!

**Comment by zelol** [comment]
I got this error when I push:

`
ERROR: Permission to mikeyhogarth/cocktails.git denied to zelol.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
`

**Comment by mikeyhogarth** [comment]
Yeah you're meant to fork it and make the changes in your fork, then make a PR from there.

**Comment by zelol** [comment]
That's it! #114
