### ISSUE TITLE
Add hardware support

### ISSUE THREAD

**Issue by kagjerde** [mikeyhogarth/cocktails#123]
Is it possible to add a "ORDER" button to the selected drink menu? and have this button send the list of ingredients and measure to  a serial port? 

The idea it to make your program a front-end for a drink mixing machine, like: https://www.youtube.com/watch?v=49msONntdEQ
These machines typically have an Arduino or some sort of microcontroller connected via USB serial to the host PC.

A program on the Arduino will then control motor and pumps, LED's, etc.

**Comment by mikeyhogarth** [comment]
So - yes it is absolutely possible for this to act as a frontend for something like that - in fact it's built in such a way that adding extensions to bring in other functionality should be a doddle. So if you're asking if it's possible - yes absolutely and you are very welcome to fork the code and do that if you want to (it's GPL licensed) but personally I'm not going to put that feature into this repository as that's not what it's for (this is just a UI for browsing cocktails),

**Comment by mikeyhogarth** [comment]
Also as an aside: I'm not sure you could automate the creation of cocktails - it's a nice idea but I think there's a bit more to it than just putting things together and stirring them (sometimes that's all there is but there's also other more physical techniques sometimes required)

**Comment by kagjerde** [comment]
Further to the above, I have added a button in the CocktailPage.js code, that send a GET post to a web server hosted on a ESP32, this works (I have simulated the reply for now) but I have problem extracting the drink information from the main application. Serial does not work in a WEB application in JS.
I have tried different things, but since your application is only providing DOM (WEB) replies, it is difficult to extract the following:
- Name of drink
- Content (Vodka, Gin, etc)
- Measure (xx cl, etc)
Ideally there should be a Javascript to provide the data in JSON format for easy transfer to a 3.rd party system.

Can you please comment, if you know of a easy way to extract the data from the Coctail page? or if an existing JS can be used for this purpose.

Thanks again,
Kjell

**Comment by kagjerde** [comment]
This is the revised code if you wnat to try (in CoctailPage.JS):
...
const CocktailPage = ({ cocktail, enrichCocktail, classes }) => {
  useScrollTop();

  if (!cocktail) return <span>Cocktail Not Found</span>;

  enrichCocktail(cocktail);
  const image = cocktail.enrichment && cocktail.enrichment.image;
  
  function UserAction() {
    var xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function() {
         if (this.readyState === 4 && this.status === 200) {
             alert(this.responseText);
         }
    };
    xhttp.open('POST', 'http://10.0.0.69:1880/update-sensor/', true);
    xhttp.setRequestHeader("Content-type", "application/json;charset=UTF-8");
    xhttp.send(JSON.stringify({cocktail: "Angel Face", gin: "3 cl", apricot_brandy: "3 cl", calvados: "3 cl"}));
  }

  return (
    <>
      <Box
        component="div"
        className={classes.mobileImage}
        display={{ xs: "block", md: "none" }}
        style={{ backgroundImage: `url(${image})` }}
      />
      <Grid container className={classes.root}>
        <Grid className={classes.cocktailDetail} item md={6} xs={12}>
          <div className={classes.cocktailDetailContent}>
            <CocktailDetail cocktail={cocktail} />
            <Button
              className={classes.Button}
              onClick={UserAction}
              >
              <h1>Order Here !</h1>
            </Button>
            <CocktailVariantList cocktail={cocktail} />
          </div>
        </Grid>
        <Grid item md={6} xs={false}>
          <Fade in={!!image}>
            <div
              style={{
                backgroundImage: `url(${image})`
              }}
              className={classes.cocktailImage}
            />
          </Fade>
        </Grid>
      </Grid>
    </>
  );
};

**Comment by kagjerde** [comment]
Sucess - I have changed the code to: (in CoctailPage.JS):
```javascript
function UserAction() {
    var xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function() {
         if (this.readyState === 4 && this.status === 200) {
             //alert(this.responseText);
         }
    };
    xhttp.open('POST', 'http://10.0.0.69:1880/update-sensor', true);
    xhttp.setRequestHeader("Content-type", "application/json;charset=UTF-8");
    const currentCoctail={cocktail};
    var name = currentCoctail.cocktail.name;
    var obj = currentCoctail.cocktail.ingredients;
    xhttp.send(JSON.stringify({name, obj}));
  }
```

This works like a charm - the message is sent via POST, and received as JSON data with all required information.

**Comment by mikeyhogarth** [comment]
Sorry mate, only just saw this. The entire cocktail information is accessible from the redux store - not sure how much react/redux/js you know but you can basically dip into the store to get any information you want - let me know if you need me to show you how to do this. 

What're you up to anyway? Sounds exciting - keep me in the loop!

**Comment by mikeyhogarth** [comment]
I was thinking - if you didn't want to use http then bluetooth is an option - chrome has a bluetooth API now.
