### ISSUE TITLE
Check necessary ingredients which aren’t included in filters

### ISSUE THREAD

**Issue by laurahogarth** [mikeyhogarth/cocktails#48]
Some cocktails require ingredients to make which aren’t taken into account when filtering. 
Examples:
- Ramos Fizz requires egg white, orange flower water, vanilla extract and soda water but these aren't available to add to "my bar", so it shows up as available to make if you have the other ingredients.
- Russian Spring Punch: preparation method says "top up with sparkling wine", but that's not listed as an ingredient.
- Derby: the only listed ingredient is gin, but you can't really make it without the other items.

**Comment by mikeyhogarth** [comment]
What do you want to do about this? You don't want every single "special" ingredient to be in the filters or there'll be a billion filters and it'll be difficult to use. Is it just the ones above that you think are problems or are there more?

**Comment by mikeyhogarth** [comment]
Done the egg white one.
