### ISSUE TITLE
exploring a collaboration between projects

### ISSUE THREAD

**Issue by atherdon** [mikeyhogarth/cocktails#78]
i'm interested to chat with repo owner

**Comment by mikeyhogarth** [comment]
Hello!

**Comment by atherdon** [comment]
Hi Mikey, thanks for your reply!
I'm building a network of food tech projects that like yours and mine. The main goal is to save time for small projects by building small modules that can be reusable between different projects. I created a long thread at Hackernoon Forum where I explain things in details - tell me if you want to read it

Arthur

**Comment by mikeyhogarth** [comment]
That does sound cool - probably not something I can dedicate any time to but am interested to read your thread.

**Comment by atherdon** [comment]
https://community.hackernoon.com/t/food-alliance-project-diary/2034/
