### ISSUE TITLE
Glass-specific SVGs

### ISSUE THREAD

**Issue by mikeyhogarth** [mikeyhogarth/cocktails#99]
At the moment we are using one SVG to represent the concept of a 'glass';
```
import CocktailIcon from "@material-ui/icons/LocalBar";
```
It would be really cool if this SVG was tailored for each glass type. There are silhouettes of them at the bottom of this wikipedia page;

https://en.wikipedia.org/wiki/List_of_glassware

My only reservation with this is that the current image of the cocktail glass we're using is very definitively representative of the concept "Glass" - some of the other glasses are just going to look like little rectangles and it might make it less obvious what they represent if they're viewed in isolation. All depends on how good the SVGs are I suppose.

**Comment by pkrawc** [comment]
Found on your Reddit thread and thought I'd offer assistance for making the svgs if you want.

I agree about your reservation but think it could be solved by adding ice cubes to the highball etc.

**Comment by mikeyhogarth** [comment]
What I might do is create the framework around it e.g. set up the folder and just put the martini-glass SVG in there for all of them, that way we could add the new glass SVGs one at a time.

**Comment by pkrawc** [comment]
I would make a component out of it that takes a type and defaults to the Martini glass.


 ```jsx
<Glass type="highball" />
```

**Comment by mikeyhogarth** [comment]
^^ Great minds 👀Okay I'll merge this in, if you want to have a play then go ahead 😃 It should just be a case of replacing the SVGs in the `images/glasses` folder and the rest should just work. Bear in mind there are rules about SVGs in MUI (I've added this as a comment in the `GlassIcon` component)

**Comment by mikeyhogarth** [comment]
Okay I did a Margarita - SVGs is *not* my strong point but it has proved I think that this is going to look totally badass with the different glasses :)

**Comment by mikeyhogarth** [comment]
Okay I did a bunch more - not going to do any more tonight but our fears have been confirmed and it just looks like a bunch of little squares (although, that is mainly going to be to do with the fact that I've never done an SVG before tonight!) - if you think you can do better @pkrawc or if you want to pick up any of the others, be my guest!

I added the icons to the glasses filter dialog too, so a good way to see them "all together" is if you filter by glass.

**Comment by mikeyhogarth** [comment]
<img width="641" alt="Screenshot 2019-06-29 at 20 37 14" src="https://user-images.githubusercontent.com/1170762/60388747-b9e01180-9aad-11e9-93ae-04fc5d5b1382.png">

**Comment by mikeyhogarth** [comment]
Alright I'm closing this ticket as all glasses now have SVGs - @pkrawc if you think you can improve them then by all means send me a PR - I really suck at SVGs it turns out!

**Comment by jcnh74** [comment]
So late to this party. Awesome stuff.
